"""improve rating constraints

Revision ID: 63e058ed3fba
Revises: a5e72ae7bac1
Create Date: 2026-02-15 10:18:00.471594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e058ed3fba'
down_revision: Union[str, Sequence[str], None] = 'a5e72ae7bac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('unique_rating_per_transaction', 'ratings', ['transaction_id', 'rater_id'])
    op.drop_constraint(op.f('ratings_ratee_id_fkey'), 'ratings', type_='foreignkey')
    op.drop_constraint(op.f('ratings_rater_id_fkey'), 'ratings', type_='foreignkey')
    op.drop_constraint(op.f('ratings_transaction_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'users', ['ratee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'users', ['rater_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_transaction_id_fkey'), 'ratings', 'transactions', ['transaction_id'], ['id'])
    op.create_foreign_key(op.f('ratings_rater_id_fkey'), 'ratings', 'users', ['rater_id'], ['id'])
    op.create_foreign_key(op.f('ratings_ratee_id_fkey'), 'ratings', 'users', ['ratee_id'], ['id'])
    op.drop_constraint('unique_rating_per_transaction', 'ratings', type_='unique')
    op.drop_column('ratings', 'created_at')
    # ### end Alembic commands ###
